export const UserData = [
    {
      id: 1,
      year: 2016,
      userGain: 80000,
      userLost: 823,
    },
    {
      id: 2,
      year: 2017,
      userGain: 45677,
      userLost: 345,
    },
    {
      id: 3,
      year: 2018,
      userGain: 78888,
      userLost: 555,
    },
    {
      id: 4,
      year: 2019,
      userGain: 90000,
      userLost: 4555,
    },
    {
      id: 5,
      year: 2020,
      userGain: 4300,
      userLost: 234,
    },
  ];

  export const ImmatriculationsData = [
    {
      id: "1",
      exploitation: 'VA',
      numImmatriculation: 'VA-0000-A',
      marque: 'Toyota',
      modele: 'Corolla',
      annee: 2021,
      carosserie: 'Berline',
      energie: 'Essence',
      ministere: 'Ministère de la santé',
      status: 'Soumis',
      provenance: 'Inde',
      genre: 'Vehicule léger',
      type: 'Voiture',
      chassis: 'KLHDFD5454DFD',
      portes: 4,
      placesAssises: 5,
      placesDebout: 0,
      dateMiseEnCirculation: '12/05/2019',
      ancienNumeroImmat: 'RC-2623-B',
      kilometrage: 2000,
      cylindre: 2,
    },
    {
      id: '2',
      exploitation: 'VA',
      numImmatriculation: 'VA-0001-A',
      marque: 'Mazda',
      modele: 'M',
      annee: 2018,
      carosserie: 'Berline',
      energie: 'Essence',
      ministere: 'Ministère de la santé',
      status: 'Soumis',
      provenance: 'Inde',
      genre: 'Vehicule léger',
      type: 'Voiture',
      chassis: 'KLHDFD5454DFD',
      portes: 4,
      placesAssises: 5,
      placesDebout: 0,
      dateMiseEnCirculation: '12/05/2019',
      ancienNumeroImmat: 'RC-2623-B',
      kilometrage: 2000,
      cylindre: 2,
    },
    {
      id: '3',
      exploitation: 'VA',
      numImmatriculation: 'VA-0002-A',
      marque: 'Mercedes',
      modele: 'Benz',
      annee: 2021,
      carosserie: 'SUV',
      energie: 'Hybride',
      ministere: 'Ministère du transport',
      status: 'Validé',
      provenance: 'Inde',
      genre: 'Vehicule léger',
      type: 'Voiture',
      chassis: 'KLHDFD5454DFD',
      portes: 4,
      placesAssises: 5,
      placesDebout: 0,
      dateMiseEnCirculation: '12/05/2019',
      ancienNumeroImmat: 'RC-2623-B',
      kilometrage: 2000,
      cylindre: 2,
    },
    {
      id: '4',
      exploitation: 'VA',
      numImmatriculation: 'VA-0003-A',
      marque: 'Land Rover',
      modele: 'Evoque',
      annee: 2016,
      carosserie: 'SUV',
      energie: 'Electrique',
      ministere: 'Ministère des mines',
      status: 'Validé',
      provenance: 'Inde',
      genre: 'Vehicule léger',
      type: 'Voiture',
      chassis: 'KLHDFD5454DFD',
      portes: 4,
      placesAssises: 5,
      placesDebout: 0,
      dateMiseEnCirculation: '12/05/2019',
      ancienNumeroImmat: 'RC-2623-B',
      kilometrage: 2000,
      cylindre: 2,
    },
  ]